from typing import Any


def _to_float(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def detect_vpn(features: dict[str, Any], model: dict[str, Any]) -> bool:
    """Return True when a flow is likely VPN traffic.

    This reference detector consumes the JSON generated by train.py. Miners can
    replace this implementation, but the function signature is the v2 contract.
    """
    fwd_bytes = _to_float(features.get("fwd_sum_pkt_len"))
    bwd_bytes = _to_float(features.get("bwd_sum_pkt_len"))
    ratio = bwd_bytes / fwd_bytes if fwd_bytes > 0 else bwd_bytes
    threshold = _to_float(model.get("ratio_threshold"))
    return ratio >= threshold


__all__ = ["detect_vpn"]
